services:
  auth:
    extends:
      file: ./localKeycloak/docker-compose.yml
      service: auth

  minio:
    extends:
      file: ./localMinio/docker-compose.yml
      service: minio

  postgres:
    extends:
      file: ./database/docker-compose.yml
      service: postgres

  elasticmq:
    image: softwaremill/elasticmq-native:1.7.1
    ports:
      - '127.0.0.1:9324:9324'
    volumes:
      - ./elasticmq/elasticmq.conf:/opt/elasticmq.conf:ro

volumes:
  postgres_data:
