version: "3.7"

services:
  postgres:
    image: postgres:15.4-alpine@sha256:35ce2187f2f7fb75e8e79493e13743596c21eb3789ff41ece145ae04d06e93a5
    container_name: "ochocast-db"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ochocast-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
