version: "3.7"

services:
  postgres:
    image: postgres:18.3-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
    container_name: "ochocast-db"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ochocast-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
