import { Injectable, Inject } from '@nestjs/common';
import { PollObject, CreatorInfo } from '../poll';
import { IPollsGateway } from '../gateways/polls.gateway';
import { PollTimerService } from '../../infra/services/poll-timer.service';

@Injectable()
export class CreatePollUsecase {
  constructor(
    @Inject('IPollsGateway')
    private readonly pollsGateway: IPollsGateway,
    private readonly pollTimerService: PollTimerService,
  ) {}

  async execute(
    question: string,
    responses: string[],
    duration: number,
    trackId: string,
    createdBy: CreatorInfo,
  ): Promise<PollObject> {
    const poll = new PollObject(
      '', // ID will be generated by the repository
      question,
      responses,
      'active',
      duration,
      trackId,
      createdBy,
      new Date(),
      {}, // voteCount
      0, // totalVotes
    );

    const createdPoll = await this.pollsGateway.createPoll(poll);

    // Schedule this poll to close at the exact moment it should expire
    this.pollTimerService.schedulePollClose(createdPoll.id, duration);

    return createdPoll;
  }
}
