include classpath("application.conf")

node-address {
  protocol = http
  host = 127.0.0.1
  port = 9324
  context-path = ""
}

aws {
  region = fr-par
  accountId = 000000000000
}

queues {
  ochocast-local-ffmpeg {
    defaultVisibilityTimeout = 3900 seconds
    receiveMessageWait = 0 seconds
  }
}
