import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: 'category',
      label: 'Utilisation',
      items: [{ type: 'autogenerated', dirName: 'documentation/utilisation'}],
    },
    {
      type: 'category',
      label: 'Administration',
      items: [{ type: 'autogenerated', dirName: 'documentation/administration'}],
    },
    {
      type: 'category',
      label: 'Contribution',
      items: [{ type: 'autogenerated', dirName: 'documentation/contribution'}],
    },
  ],
};

export default sidebars;
